title: Sun Seeds
description: >- # this means to ignore newlines until "baseurl:"
  Kits for making interlocking, curved-origami sculptures that change color in the sunlight
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

sunseeds:
  - name: Star Flower
    slug: starflower
  - name: Succulent
    slug: succulent
  - name: Daisy
    slug: daisy
  - name: Mint
    slug: mint
  - name: Lotus
    slug: lotus
  - name: Passion
    slug: passion

exclude:
  - .DS_Store
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
